Interview goal
enioka-Haute-Couture/pyoupyou pull request #188
Opened 2021-12-09 10:24 UTC by ArnaudChirat

2021-12-30 07:40 UTC, bport commented on interview/views.py
> +        next_goal = Interview.objects.filter(process=process).exclude(next_interview_goal="").last()
Next goal need to be current interview goal or previous interview next goal.
We need to create a new database field to handle that

2022-01-13 10:47 UTC, bport requested changes
Perhaps on new interview form, we can display next goal somewhere and add placeholder to explain that we need to enter a goal only if goal differs

2022-01-13 10:47 UTC, bport commented on interview/views.py
> +    except:
Catch only needed exception

2022-01-13 10:47 UTC, bport commented on interview/views.py
> +    except:
I will avoid inline if else when we are not in the same line

2022-01-13 10:47 UTC, bport commented on locale/fr/LC_MESSAGES/django.po
> +#, fuzzy
this line is marked as fuzzy fix it

2022-01-13 10:56 UTC, ArnaudChirat commented
> Perhaps on new interview form, we can display next goal somewhere and add placeholder to explain that we need to enter a goal only if goal differs

2022-01-13 10:57 UTC, ArnaudChirat commented
> Perhaps on new interview form, we can display next goal somewhere and add placeholder to explain that we need to enter a goal only if goal differs

May be we can preload the form with next_goal

2022-09-08 08:55 UTC, bport requested changes

2022-09-08 08:55 UTC, bport commented on interview/views.py
> +            goal = Interview.objects.filter(process=interview.process).reverse()[2].next_interview_goal
I think we can use rank to get previous one

2022-12-13 10:17 UTC, merged