225 create a development dataset
enioka-Haute-Couture/pyoupyou pull request #231
Opened 2022-10-26 13:09 UTC by rnudb

2022-10-27 13:45 UTC, ArnaudChirat commented
The CHANGELOG and the README must be update

2022-10-27 15:52 UTC, ArnaudChirat approved these changes

2022-11-02 10:50 UTC, bport requested changes

2022-11-02 10:50 UTC, bport commented on CHANGELOG.md
> +# v1.16.0 (2022-10-27)
mettre xxxx-xx-xx à la palce de la date on a pas encore de date de release

2022-11-02 10:50 UTC, bport commented on interview/management/commands/create_dev_dataset.py
> +    if len(possible_interviewer) == 0:
We can write directly

if possible_interviewer:

2022-11-02 10:50 UTC, bport commented on interview/factory.py
> +import random
don't use random we want the ability in future to have something seeded and use faker everywhere will ease that

2022-11-02 10:50 UTC, bport commented on interview/management/commands/create_dev_dataset.py
> +        # call_command("flush", "--no-input") # dev
This comment need to go to readme I guess

2022-11-02 10:50 UTC, bport commented on interview/management/commands/create_dev_dataset.py
> +    if InterviewKind.objects.all().count() == 0:
Why are we checking that ? (apply to same stuff below)
If we wanted to check that we can use .`exists()`

2022-11-02 10:50 UTC, bport commented on interview/management/commands/create_dev_dataset.py
> +            InterviewKindFactory(name="Interview Kind {no}".format(no=i))
I think the factory need to generate random name by it self and we don't need to put extra argument there

2022-11-04 08:41 UTC, merged