235 connection to cognito form
enioka-Haute-Couture/pyoupyou pull request #236
Opened 2022-11-07 15:14 UTC by rnudb

2022-11-07 15:26 UTC, bport requested changes

2022-11-07 15:26 UTC, bport commented on interview/views.py
> +                print("Created document")
Delete print

2022-11-07 15:26 UTC, bport commented on interview/views.py
> +        process_data["other_informations"] += " - Disponible dès: " + data["Availability"]
We have a dedicated field for that

2022-11-07 15:26 UTC, bport commented on interview/views.py
> +                file_tmp = NamedTemporaryFile(delete=True, suffix=".pdf")
I guess we can have something else than pdf, use file name to get extension

2022-11-07 15:26 UTC, bport commented on pyoupyou/settings/dev.py
> +FORM_WEB_HOOK_PREFIX = "wefstcaticnbhmnhbkyqbbaqwxlxgbta"
replace with "dev" easiest for test locally and we don't want security on our local machine

2022-11-07 15:26 UTC, bport commented on interview/views.py
> +        candidate_data["linkedin_url"] = data["Linkedin"]
This field don't exist ?

2022-11-07 15:26 UTC, bport commented on pyoupyou/urls.py
> +        csrf_exempt(views.process_from_cognito_form),
set csrf_exempt as decorator on the function directly

2022-11-07 15:26 UTC, bport commented on interview/tests.py
> +        for i in range(6):
Tips change json so we don't need to create 6 :-)

2022-11-07 16:54 UTC, bport requested changes

2022-11-07 16:54 UTC, bport commented on interview/views.py
> +    # TODO: rebase on 226 to have linkedin field in candidate
I guess it's done :-)

2022-11-07 16:54 UTC, bport commented on interview/tests.py
> +        # create 6 offer as offer id in request is 5
can remove comment :-)

2022-11-07 16:54 UTC, bport commented on interview/tests.py
> +            "Name": self.candidate.name,
Don't use factory there, hard code a name, email and phone

2022-11-08 12:51 UTC, ArnaudChirat commented on interview/views.py
> +                    r = requests.get(document["File"], stream=True)
You need to close the file

2022-11-10 09:30 UTC, ArnaudChirat commented on interview/tests.py
> +class ImportCognitoFormTestCase(TestCase):
You need a test with documents

2022-11-10 09:30 UTC, ArnaudChirat commented on interview/serializers.py
> +            r = requests.get(document["File"], stream=True)
how do you get the request ?

2022-11-10 13:40 UTC, ArnaudChirat commented on interview/views.py
> +    serializer.is_valid(raise_exception=True)
return bad request if not valid (even if cognito doesnt care, it is usefull for debug)

2022-11-10 13:49 UTC, ArnaudChirat approved these changes

2022-12-27 08:52 UTC, merged