Add ExternalConsultant & basic logic for it
enioka-Haute-Couture/pyoupyou pull request #241
Opened 2022-11-15 16:53 UTC by rnudb

2022-11-17 14:44 UTC, rnudb commented on interview/views.py
> +        if request.user.consultant.company:
needs changes: an external consultant is always linked to a subsidiary

2022-11-17 14:52 UTC, rnudb commented on ref/models.py
> +    to_source = models.ForeignKey("interview.Sources", null=True, default=None, on_delete=models.SET_NULL)
add blank=True

2022-11-21 08:34 UTC, bport requested changes

2022-11-21 08:59 UTC, rnudb commented on interview/views.py
> +    if request.user.consultant.to_source:
External user can and will reach this line. If we remove it, the source field will appear in the form which is not what's wanted (source predefined => no source field).

2022-11-21 08:59 UTC, rnudb commented on interview/views.py
> +    if request.user.consultant.to_source:
Same as above comment

2022-11-21 09:15 UTC, bport commented on interview/views.py
> +    if request.user.consultant.to_source:
my bad

2022-11-22 08:53 UTC, bport requested changes
Add some test to ensure all work as expected (don't need to have a test for each view)

But at least :
Test external user access on a page with right, on a source page not allow, external without source associated to him.

2022-11-22 08:53 UTC, bport commented on ref/models.py
> +    ALL = 1
Use IntegerChoice enum style

https://docs.djangoproject.com/en/3.2/ref/models/fields/#enumeration-types

2022-11-22 08:53 UTC, bport commented on ref/models.py
> +        "interview.Sources", null=True, blank=True, default=None, on_delete=models.DO_NOTHING
I don't think we want DO_NOTHING, this will raise a constraint error

2022-11-22 08:53 UTC, bport commented on ref/models.py
> +        choices=PRIVILEGE_LEVEL, verbose_name=_("Authority level"), default=ALL
We need to translate it

2022-11-24 17:41 UTC, ArnaudChirat requested changes
Add middleware to check if user is valid.
- If external is correct

2022-11-24 17:41 UTC, ArnaudChirat commented on interview/models.py
> +        if user.consultant.privilege > Consultant.PrivilegeLevel.ALL:
Add a property to the model to avoid change every where in the code if the logic change

2022-11-24 17:41 UTC, ArnaudChirat commented on interview/models.py
> +        if user.consultant.privilege > Consultant.PrivilegeLevel.ALL:
What is the difference between > Consultant.PrivilegeLevel.ALL and is_external ?

2022-11-24 17:41 UTC, ArnaudChirat commented on interview/views.py
> +    if request.user.consultant.privilege > Consultant.PrivilegeLevel.ALL and (  # is consultant external ?
Why not using the decorator is_external ?

2022-11-29 10:40 UTC, ArnaudChirat requested changes

2022-11-29 10:40 UTC, ArnaudChirat commented on interview/tests.py
> +
Add a test for the middleware

2022-11-29 13:03 UTC, rnudb commented on interview/tests.py
> +
Done !

2022-11-30 08:35 UTC, ArnaudChirat approved these changes

2022-12-07 11:01 UTC, merged