#237 Fix testsuite random crash
enioka-Haute-Couture/pyoupyou pull request #250
Opened 2022-12-14 08:57 UTC by rnudb

2022-12-19 10:26 UTC, ArnaudChirat approved these changes

2022-12-19 10:27 UTC, ArnaudChirat approved these changes

2022-12-29 09:05 UTC, bport commented on CHANGELOG.md
> +# v1.18.0 (xxx-xx-xx)
We will have only 1.17 release you need to put it under 1.17 version

2022-12-29 09:16 UTC, bport requested changes

2022-12-29 09:16 UTC, bport commented on ref/factory.py
> +            return code
I guess you want to use permutations, something like:
 
```python
for c in ["".join(perm).upper() for perm in itertools.permutations(s, 3)]:
    if c.isalpha() and c not in all_codes:
         return c
```

2022-12-29 09:20 UTC, rnudb commented on ref/factory.py
> +            return code
In our case combinations make more sense than permutations as we want to keep better readability. Though the way you wrote it is much cleaner, I'll update the code.

2023-01-02 10:17 UTC, merged