Update candidates anonymization
enioka-Haute-Couture/pyoupyou pull request #326
Opened 2024-02-07 10:05 UTC by abessette

2024-02-14 14:14 UTC, bport requested changes

2024-02-14 14:14 UTC, bport commented on interview/views.py
> -            if not candidate.name:
We need to keep those checks for merging candidates

i.e. if the existing one contains phone number and not the new one, we want to keep this information from the old one

2024-02-16 09:51 UTC, abessette commented on interview/views.py
> -            if not candidate.name:
Thank you for spotting this.
Please find below an associated fix.

2024-02-29 14:58 UTC, bport requested changes

2024-02-29 14:58 UTC, bport commented on interview/models.py
> +        self.save()
Don't save both here and on caller code

2024-02-29 14:58 UTC, bport commented on interview/management/commands/anonymize.py
> +                proc.save()
We need to prevent email triggering

2024-03-06 13:02 UTC, bport commented on interview/models.py
> +        super(Interview, self).save(force_insert=False, force_update=False, using=None, update_fields=None)
We don't want to force value to save method

2024-03-14 08:51 UTC, merged